services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER-user}
        uid: ${UID-1000}
    image: altertrack-app
    container_name: altertrack-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
